# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'regr_calc.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1082, 330)
        self.nn_field = QtWidgets.QLineEdit(Form)
        self.nn_field.setGeometry(QtCore.QRect(30, 140, 41, 22))
        self.nn_field.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.nn_field.setObjectName("nn_field")
        self.tn_field = QtWidgets.QLineEdit(Form)
        self.tn_field.setGeometry(QtCore.QRect(140, 140, 41, 22))
        self.tn_field.setObjectName("tn_field")
        self.tr_field = QtWidgets.QLineEdit(Form)
        self.tr_field.setGeometry(QtCore.QRect(230, 140, 41, 22))
        self.tr_field.setObjectName("tr_field")
        self.cwt_filed = QtWidgets.QLineEdit(Form)
        self.cwt_filed.setGeometry(QtCore.QRect(450, 140, 101, 22))
        self.cwt_filed.setReadOnly(False)
        self.cwt_filed.setClearButtonEnabled(False)
        self.cwt_filed.setObjectName("cwt_filed")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 110, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(120, 110, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(240, 110, 21, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(300, 110, 121, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(440, 110, 131, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(590, 110, 111, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(740, 110, 111, 16))
        self.label_7.setObjectName("label_7")
        self.pu_field = QtWidgets.QLineEdit(Form)
        self.pu_field.setGeometry(QtCore.QRect(300, 140, 121, 22))
        self.pu_field.setObjectName("pu_field")
        self.iwt_filed = QtWidgets.QLineEdit(Form)
        self.iwt_filed.setGeometry(QtCore.QRect(600, 140, 91, 22))
        self.iwt_filed.setReadOnly(False)
        self.iwt_filed.setClearButtonEnabled(False)
        self.iwt_filed.setObjectName("iwt_filed")
        self.cu_field = QtWidgets.QLineEdit(Form)
        self.cu_field.setGeometry(QtCore.QRect(750, 140, 81, 22))
        self.cu_field.setReadOnly(False)
        self.cu_field.setClearButtonEnabled(False)
        self.cu_field.setObjectName("cu_field")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(910, 110, 151, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_8.setPalette(palette)
        self.label_8.setObjectName("label_8")
        self.nrt_field = QtWidgets.QLineEdit(Form)
        self.nrt_field.setGeometry(QtCore.QRect(940, 140, 81, 22))
        self.nrt_field.setReadOnly(True)
        self.nrt_field.setClearButtonEnabled(False)
        self.nrt_field.setObjectName("nrt_field")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(400, 240, 231, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Node Number"))
        self.label_2.setText(_translate("Form", "Thread Number"))
        self.label_3.setText(_translate("Form", "T/R"))
        self.label_4.setText(_translate("Form", "Processor Utilisation"))
        self.label_5.setText(_translate("Form", "Channel Waiting Time"))
        self.label_6.setText(_translate("Form", "Input Waiting Time"))
        self.label_7.setText(_translate("Form", "Channel Utilisation"))
        self.label_8.setText(_translate("Form", "Network Response Time"))
        self.pushButton.setText(_translate("Form", "Вычислить предсказание"))

